name: Create Classic Project

on:
  workflow_dispatch:

jobs:
  create_project:
    runs-on: ubuntu-latest
    steps:
      - name: Create Classic Project using REST API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            https://api.github.com/repos/$REPO/projects \
            -d '{"name":"GitHub Actions Project","body":"Created by workflow"}'
