name: Create Classic Project
on:
  workflow_dispatch:

jobs:
  create_project:
    runs-on: ubuntu-latest
    steps:
      - name: Create Classic Project using REST API
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            https://github.com/repos/${{ github.repository }}/projects \
            -d '{"name":"My New Project","body":"Created by GitHub Actions"}'
