name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python project-ceation.py
