name: Create Organization Project

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Organization Name'
        required: true
      project_name:
        description: 'Project Name'
        required: true
      project_body:
        description: 'Project Description'
        required: false

jobs:
  create_project:
    runs-on: ubuntu-latest
    steps:
      - name: Create Organization Project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const org = '${{ github.event.inputs.org }}'
            const name = '${{ github.event.inputs.project_name }}'
            const body = '${{ github.event.inputs.project_body || '' }}'

            const response = await github.rest.projects.createOrgProject({
              org,
              name,
              body,
            });

            core.info(`Created Project: ${response.data.html_url}`);
